export interface pictitem {
    name: string,
    src: string,
    fname: string,
}


export const chpict : Array<pictitem> = [
    {name: "Болоньєзе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/sHypmOD-kUfrgzF-XjkkIBX.jpeg", fname: "sHypmOD-kUfrgzF-XjkkIBX.jpeg"},
    {name: "Паста з сирним соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kHQwIW-ntVDCRH-lFClLzQ.jpeg", fname: "kHQwIW-ntVDCRH-lFClLzQ.jpeg"},
    {name: "Паста карбонара",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tQnBFAM-cJsEUX-cSNvdLu.jpeg", fname: "tQnBFAM-cJsEUX-cSNvdLu.jpeg"},
    {name: "Паста домашняя с куриным мясом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WFHplDe-EfvaNWE-jQqhoU.jpeg", fname: "WFHplDe-EfvaNWE-jQqhoU.jpeg"},
    {name: "Салат з тунцем гриль і горіховим соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RqHKNJq-LuqoKRN-sxQuVv.jpeg", fname: "RqHKNJq-LuqoKRN-sxQuVv.jpeg"},
    {name: "Тайський салат з телятиною і рисовою локшиною",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GAJOyTC-uxTIEcX-RCEwObx.jpeg", fname: "GAJOyTC-uxTIEcX-RCEwObx.jpeg"},
    {name: "Лаваш з індичкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/XFeGXSt-GgQelxx-xftdmKt.jpeg", fname: "XFeGXSt-GgQelxx-xftdmKt.jpeg"},
    {name: "Лаваш з моцарелою і зеленню",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/MFUDkxe-SsGnqGA-wlxxMIR.jpeg", fname: "MFUDkxe-SsGnqGA-wlxxMIR.jpeg"},
    {name: "Лаваш з курячим філе і томатами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QJLQsfV-fafcwSm-HlunInk.jpeg", fname: "QJLQsfV-fafcwSm-HlunInk.jpeg"},
    {name: "Лаваш з телятиною і грибами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FVHpFyg-rBJnrpD-bLinkeD.jpeg", fname: "FVHpFyg-rBJnrpD-bLinkeD.jpeg"},
    {name: "Лаваш з курячим стегном",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HudkNRA-eDnzkEj-TFpUDU.jpeg", fname: "HudkNRA-eDnzkEj-TFpUDU.jpeg"},
    {name: "Лосось з овочами гриль",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/LCZktrC-mTqFfgu-bfcJPpw.jpeg", fname: "LCZktrC-mTqFfgu-bfcJPpw.jpeg"},
    {name: "Форель по-карпатски",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RfLNlDP-eIIDCwB-lDydCbV.jpeg", fname: "RfLNlDP-eIIDCwB-lDydCbV.jpeg"},
    {name: "Рибна сковорідка",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/wYebCNy-JVlJhjN-EohrUBE.jpeg", fname: "wYebCNy-JVlJhjN-EohrUBE.jpeg"},
    {name: "Крила фрі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/NuEIGcL-rcfNmuW-JciiPdH.jpeg", fname: "NuEIGcL-rcfNmuW-JciiPdH.jpeg"},
    {name: "Курка в кисло-солодкому соусі з чіпсами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/cHIHZkV-iQsDNbC-sJkJChk.jpeg", fname: "cHIHZkV-iQsDNbC-sJkJChk.jpeg"},
    {name: "Креветки фрі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/AeZloOw-twDmQCU-WlIQzm.jpeg", fname: "AeZloOw-twDmQCU-WlIQzm.jpeg"},
    {name: "Тар-тар из телятины",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/hHBJEHl-tqdVDQt-GxYLbfO.jpeg", fname: "hHBJEHl-tqdVDQt-GxYLbfO.jpeg"},
    {name: "Свинина в гострому соусі з чіпсами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ASoIpBM-ylBMYeN-KJoEVkO.jpeg", fname: "ASoIpBM-ylBMYeN-KJoEVkO.jpeg"},
    {name: "Свинина барбекю з картоплею по-креольськи",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/AjmClGg-yhuANqu-zbTlxeR.jpeg", fname: "AjmClGg-yhuANqu-zbTlxeR.jpeg"},
    {name: "Телятина на овочевій подушці з винним соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OFXuIdj-LbXymPK-CiTqXBD.jpeg", fname: "OFXuIdj-LbXymPK-CiTqXBD.jpeg"},
    {name: "Стейк зі свинини з картопляним пюре і соусом сальса",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jRDbLgf-ZDYwCXk-xeqheIX.jpeg", fname: "jRDbLgf-ZDYwCXk-xeqheIX.jpeg"},
    {name: "Тальята з телятини",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/IOYqreb-UtOlbZC-bCRGlTe.jpeg", fname: "IOYqreb-UtOlbZC-bCRGlTe.jpeg"},
    {name: "Філе індички з овочевим рататуєм і трюфеля пастою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FCLHlRq-ASZLTYO-ubMeAZp.jpeg", fname: "FCLHlRq-ASZLTYO-ubMeAZp.jpeg"},
    {name: "Гриль сет Чилі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CFbqqgr-KIIYSoq-breMOhU.jpeg", fname: "CFbqqgr-KIIYSoq-breMOhU.jpeg"},
    {name: "Сковорідка з фермерськими ковбасками",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/lVnfkeh-bjngDz-BCwuYGn.jpeg", fname: "lVnfkeh-bjngDz-BCwuYGn.jpeg"},
    {name: "Сковорідка з курячими серцями і печінкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nJdrDt-SskFTjK-qGnHQyz.jpeg", fname: "nJdrDt-SskFTjK-qGnHQyz.jpeg"},
    {name: "Сковорідка по-домашньому",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/laRNQPF-tXdRwBl-wuudkXt.jpeg", fname: "laRNQPF-tXdRwBl-wuudkXt.jpeg"},
    {name: "Сковорідка з курячим стегном і трюфельноей пастою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ZCLopEb-IInFONb-cSGAIbw.jpeg", fname: "ZCLopEb-IInFONb-cSGAIbw.jpeg"},
    {name: "Cковорідка польова",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tyNeBHk-sTIcJOt-UldGCKM.jpeg", fname: "tyNeBHk-sTIcJOt-UldGCKM.jpeg"},
    {name: "Грецький300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OsDEdaI-xbiZFFy-oWLpUlG.jpeg", fname: "OsDEdaI-xbiZFFy-oWLpUlG.jpeg"},
    {name: "Грін-мікс з курячим філе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TgoIWZb-jFIvmPL-MYsrHzZ.jpeg", fname: "TgoIWZb-jFIvmPL-MYsrHzZ.jpeg"},
    {name: "Цезарь люкс",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HgbRFQF-aguoLIs-VLclHvH.jpeg", fname: "HgbRFQF-aguoLIs-VLclHvH.jpeg"},
    {name: "Салат з ростбіфом і цукіні гриль",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FjWzkLN-ClpIIY-HefXIDz.jpeg", fname: "FjWzkLN-ClpIIY-HefXIDz.jpeg"},
    {name: "Салат з телятиною і печерицями",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kiQHtff-sFGIur-ritKnJT.jpeg", fname: "kiQHtff-sFGIur-ritKnJT.jpeg"},
    {name: "М'ясний салат",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CkmDFqk-HDpZIPk-WAnINTU.jpeg", fname: "CkmDFqk-HDpZIPk-WAnINTU.jpeg"},
    {name: "Грецький 200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QGfTLJp-TnKQIkR-emoFJiH.jpeg", fname: "QGfTLJp-TnKQIkR-emoFJiH.jpeg"},
    {name: "Салат з камамбером фрі і апельсином",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/zGJbGfF-GIADJUJ-CpFtcRD.jpeg", fname: "zGJbGfF-GIADJUJ-CpFtcRD.jpeg"},
    {name: "Цезарь 	200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dNIHMef-sXVvVDF-IkEqwZW.jpeg", fname: "dNIHMef-sXVvVDF-IkEqwZW.jpeg"},
    {name: "Цезарь 	300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/buRMwU-kbouGrF-kmLgiDD.jpeg", fname: "buRMwU-kbouGrF-kmLgiDD.jpeg"},
    {name: "Салат з кіноа, авокадо і сиром фета",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TgkkIw-QbqIvJg-RtmoSQl.jpeg", fname: "TgkkIw-QbqIvJg-RtmoSQl.jpeg"},
    {name: "Фірмовий олів'є з лососем і креветками",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/qxJlXxB-bsyNJem-NFuXUzO.jpeg", fname: "qxJlXxB-bsyNJem-NFuXUzO.jpeg"},
    {name: "Салат з курячим філе гриль і кедровими горіхами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HoIxIgH-DaGFAhs-FyDFTHc.jpeg", fname: "HoIxIgH-DaGFAhs-FyDFTHc.jpeg"},
    {name: "Грузинський",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bOlDelJ-QjAVml-SIHyGJC.jpeg", fname: "bOlDelJ-QjAVml-SIHyGJC.jpeg"},
    {name: "Салат з курячою печінкою і свіжими томатами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ZrHWiKO-NIQsLvU-QpLfZwa.jpeg", fname: "ZrHWiKO-NIQsLvU-QpLfZwa.jpeg"},
    {name: "Гавайський з курячим філе і ананасами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nfDnhX-CkvdCSl-neStVgg.jpeg", fname: "nfDnhX-CkvdCSl-neStVgg.jpeg"},
    {name: "Овочевий мікс200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/oelGoKI-pNhDQY-FzkGQFb.jpeg", fname: "oelGoKI-pNhDQY-FzkGQFb.jpeg"},
    {name: "Овочевий Мікс 300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/yHJXmKF-hPCzRip-qsrHCol.jpeg", fname: "yHJXmKF-hPCzRip-qsrHCol.jpeg"},
    {name: "З курячим філе і вершковим соусом каррі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ikkgegJ-CHViSLG-DikDlo.jpeg", fname: "ikkgegJ-CHViSLG-DikDlo.jpeg"},
    {name: "Сільська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HhCJJJs-lIqenMI-Ousrkl.jpeg", fname: "HhCJJJs-lIqenMI-Ousrkl.jpeg"},
    {name: " Грецька",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/aGQHDfF-dYismDU-JgwucDF.jpeg", fname: "aGQHDfF-dYismDU-JgwucDF.jpeg"},
    {name: "Мисливська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ueTbCIr-YVHcLjP-JCYlVO.jpeg", fname: "ueTbCIr-YVHcLjP-JCYlVO.jpeg"},
    {name: "Формаджо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/pxbDFVk-OskQWfJ-SKHJiZr.jpeg", fname: "pxbDFVk-OskQWfJ-SKHJiZr.jpeg"},
    {name: "М'ясна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jdrXycr-fCKxeLX-bCJkltx.jpeg", fname: "jdrXycr-fCKxeLX-bCJkltx.jpeg"},
    {name: "Чориззо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iNzeFwy-cixRCdP-ClHCWkd.jpeg", fname: "iNzeFwy-cixRCdP-ClHCWkd.jpeg"},
    {name: "Міланська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/EOJeBQV-hoiWqBM-yIiIILP.jpeg", fname: "EOJeBQV-hoiWqBM-yIiIILP.jpeg"},
    {name: "Сомбреро",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ooyBcKQ-OeJKmIM-pVelpGd.jpeg", fname: "ooyBcKQ-OeJKmIM-pVelpGd.jpeg"},
    {name: "Ароматна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WjEwRcD-IqTMdGS-PbxAkHC.jpeg", fname: "WjEwRcD-IqTMdGS-PbxAkHC.jpeg"},
    {name: "Барбекю",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FuWkilt-tyPdUI-MtCHsqC.jpeg", fname: "FuWkilt-tyPdUI-MtCHsqC.jpeg"},
    {name: "Гавайська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DkpCGDC-PptctgF-zrDqQuA.jpeg", fname: "DkpCGDC-PptctgF-zrDqQuA.jpeg"},
    {name: "Кальцоне з шинкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TeGgCCk-DzXKTPQ-yYDuDVr.jpeg", fname: "TeGgCCk-DzXKTPQ-yYDuDVr.jpeg"},
    {name: "Кальцоне з курячим філе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JUvEIDD-pUxGlLC-fyTljcQ.jpeg", fname: "JUvEIDD-pUxGlLC-fyTljcQ.jpeg"},
    {name: "Кальцоне сирна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DjdTZmf-EkLeGol-JBJFzQN.jpeg", fname: "DjdTZmf-EkLeGol-JBJFzQN.jpeg"},
    {name: "Пепероні",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dAFIjxv-oVdbCYv-LtdesJV.jpeg", fname: "dAFIjxv-oVdbCYv-LtdesJV.jpeg"},
    {name: "Чілі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QGGbLVM-ixlowJ-CmjieHY.jpeg", fname: "QGGbLVM-ixlowJ-CmjieHY.jpeg"},
    {name: "Салямі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/zFpVCCy-WlRIOvT-JpIjTyv.jpeg", fname: "zFpVCCy-WlRIOvT-JpIjTyv.jpeg"},
    {name: "Поло",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/VteGlsx-bbfNXs-GkTfKXT.jpeg", fname: "VteGlsx-bbfNXs-GkTfKXT.jpeg"},
    {name: "Прошутто",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kfpcksb-QfpewN-eZxjwHx.jpeg", fname: "kfpcksb-QfpewN-eZxjwHx.jpeg"},
    {name: "Тонато",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/eCPiqmc-coDtqix-bjKbuXv.jpeg", fname: "eCPiqmc-coDtqix-bjKbuXv.jpeg"},
    {name: "Цезарь",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WjRHDkb-hipysIK-bHZkeEy.jpeg", fname: "WjRHDkb-hipysIK-bHZkeEy.jpeg"},
    {name: "Сан-марино",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/pkClOo-CYCIKIC-yRPsCUG.jpeg", fname: "pkClOo-CYCIKIC-yRPsCUG.jpeg"},
    {name: "Ростбіф",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/qnWTrq-FjwHeyr-hZJokD.jpeg", fname: "qnWTrq-FjwHeyr-hZJokD.jpeg"},
    {name: "Вилладжіо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/wrRBONR-WytwBk-xTtzvoj.jpeg", fname: "wrRBONR-WytwBk-xTtzvoj.jpeg"},
    {name: "Аматрічіано",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dHGRWo-kaJdFJU-bcbkGKm.jpeg", fname: "dHGRWo-kaJdFJU-bcbkGKm.jpeg"},
    {name: "Сирна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dUGuaRl-UeCjbQM-ZApxqHP.jpeg", fname: "dUGuaRl-UeCjbQM-ZApxqHP.jpeg"},
    {name: "Б 'ьянка",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/klMlqCh-jnbEPPu-JsBmegb.jpeg", fname: "klMlqCh-jnbEPPu-JsBmegb.jpeg"},
    {name: "Сан-Ремо + бутилка вина Villa Krim ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/XOqYkCI-IzUChXU-nyEtHe.jpeg", fname: "XOqYkCI-IzUChXU-nyEtHe.jpeg"},
    {name: "Палермо + 2л пива Carlsberg",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/MBTMFuk-QdgwZHG-swgHbeA.jpeg", fname: "MBTMFuk-QdgwZHG-swgHbeA.jpeg"},
    {name: "Наполі	+ 2л пива Kronenbourg Blanc",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tQNIFfI-lkGjvcG-eeQPCzC.jpeg", fname: "tQNIFfI-lkGjvcG-eeQPCzC.jpeg"},
    {name: "Нуталина (солодка  піца)",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/fuGesk-HnEAGH-skBZDDu.jpeg", fname: "fuGesk-HnEAGH-skBZDDu.jpeg"},
    {name: "Йору",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/YolSQIA-kThxDbZ-YmHgHEc.jpeg", fname: "YolSQIA-kThxDbZ-YmHgHEc.jpeg"},
    {name: "Запечений зелений дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/Aujrrck-cgURtxa-WdFDRFS.jpeg", fname: "Aujrrck-cgURtxa-WdFDRFS.jpeg"},
    {name: "Імбирний рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GSWrHSl-DDFjwCN-GmHyHkL.jpeg", fname: "GSWrHSl-DDFjwCN-GmHyHkL.jpeg"},
    {name: "Зелений дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/VUllXxV-eACumIm-FgIAmyk.jpeg", fname: "VUllXxV-eACumIm-FgIAmyk.jpeg"},
    {name: "Томаго",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GwzjkxJ-kRJpCDf-htqRkcl.jpeg", fname: "GwzjkxJ-kRJpCDf-htqRkcl.jpeg"},
    {name: "Кани",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CjMljcK-RjXBRo-BqSTELB.jpeg", fname: "CjMljcK-RjXBRo-BqSTELB.jpeg"},
    {name: "Парма рол з креветкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/SHbCOmH-FIwtblW-JQnykAc.jpeg", fname: "SHbCOmH-FIwtblW-JQnykAc.jpeg"},
    {name: "Кудамон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QKCbDsI-kJDFxLi-NBWsurb.jpeg", fname: "QKCbDsI-kJDFxLi-NBWsurb.jpeg"},
    {name: "Фудзі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DgCGbwV-RmHkuHE-uVZhmFb.jpeg", fname: "DgCGbwV-RmHkuHE-uVZhmFb.jpeg"},
    {name: "Самурай",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jZgbceS-HlJuURx-UjmoLrG.jpeg", fname: "jZgbceS-HlJuURx-UjmoLrG.jpeg"},
    {name: "Інь-янь",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iDUmHVt-FvHoXZ-THvtHBx.jpeg", fname: "iDUmHVt-FvHoXZ-THvtHBx.jpeg"},
    {name: "Чидорі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WoCeIUt-bmwIDCk-KNvJHMc.jpeg", fname: "WoCeIUt-bmwIDCk-KNvJHMc.jpeg"},
    {name: "Філадельфія",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bpHliyz-ikGneyv-dIBUOQG.jpeg", fname: "bpHliyz-ikGneyv-dIBUOQG.jpeg"},
    {name: "Золотий дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/xZOYDqW-BUDxYpk-SIlXHUR.jpeg", fname: "xZOYDqW-BUDxYpk-SIlXHUR.jpeg"},
    {name: "Гадо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/hvDZyG-TDnQfIg-EReQpja.jpeg", fname: "hvDZyG-TDnQfIg-EReQpja.jpeg"},
    {name: "Унагі хая",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/YPGsato-SeUxlXO-bHxIWLO.jpeg", fname: "YPGsato-SeUxlXO-bHxIWLO.jpeg"},
    {name: "Туна рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OHrJfVT-ZCctvTR-seNuqWk.jpeg", fname: "OHrJfVT-ZCctvTR-seNuqWk.jpeg"},
    {name: "Радуйга",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/abmpDwT-smmykdT-bwHkrH.jpeg", fname: "abmpDwT-smmykdT-bwHkrH.jpeg"},
    {name: "Філадельфія хаяші",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/lBUHsb-LknrLPc-gzyyDrV.jpeg", fname: "lBUHsb-LknrLPc-gzyyDrV.jpeg"},
    {name: "Такусан",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bXXjzDo-oLayEse-VnkDMNo.jpeg", fname: "bXXjzDo-oLayEse-VnkDMNo.jpeg"},
    {name: "Дайкон ролл",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ARpgtSA-ncRkkwl-eFgbJMo.jpeg", fname: "ARpgtSA-ncRkkwl-eFgbJMo.jpeg"},
    {name: "Овара",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iDroSjC-ISfODJb-zsbIkHQ.jpeg", fname: "iDroSjC-ISfODJb-zsbIkHQ.jpeg"},
    {name: "Філадельфія з кокосовим соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dLPKVkw-YfDGoSg-LFmesIl.jpeg", fname: "dLPKVkw-YfDGoSg-LFmesIl.jpeg"},
    {name: "Чілі рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JOeozjD-ZFuLjAl-MVozHr.jpeg", fname: "JOeozjD-ZFuLjAl-MVozHr.jpeg"},
    {name: "Широ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/mDiMMgg-JqZzjJh-IgxtqkL.jpeg", fname: "mDiMMgg-JqZzjJh-IgxtqkL.jpeg"},
    {name: "Запечена рол з лососем",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/NhwAXFQ-UTYLIuq-GLIgeJk.jpeg", fname: "NhwAXFQ-UTYLIuq-GLIgeJk.jpeg"},
    {name: "Сет Муракамі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FOKOxfP-TQvbtFx-XwCvbAy.jpeg", fname: "FOKOxfP-TQvbtFx-XwCvbAy.jpeg"},
    {name: "Сет Хоккайдо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nloUvYV-PbzLLG-TIIiGJX.jpeg", fname: "nloUvYV-PbzLLG-TIIiGJX.jpeg"},
    {name: "Сет Окінава",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FCnbODF-WyieuXv-WqKXGDl.jpeg", fname: "FCnbODF-WyieuXv-WqKXGDl.jpeg"},
    {name: "Сет нагоя",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DorGJWY-GQhJFHp-bVGObhD.jpeg", fname: "DorGJWY-GQhJFHp-bVGObhD.jpeg"},
    {name: "З качкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RNHDkHt-eoeSFYW-tuyfnhh.jpeg", fname: "RNHDkHt-eoeSFYW-tuyfnhh.jpeg"},
    {name: "З куркою ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JydVFg-IkfwFyp-qCVzNNC.jpeg", fname: "JydVFg-IkfwFyp-qCVzNNC.jpeg"},
    {name: "Гостра зі свининою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kDebNDR-VskPCXW-ZQoqhr.jpeg", fname: "kDebNDR-VskPCXW-ZQoqhr.jpeg"},
    {name: "З креветкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/LNkmvJe-anktrID-gnzIZFA.jpeg", fname: "LNkmvJe-anktrID-gnzIZFA.jpeg"},
    {name: "З телятиною",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/yonyPmV-yjaKem-kJIOFvc.jpeg", fname: "yonyPmV-yjaKem-kJIOFvc.jpeg"},
    
    
]