export interface pictitem {
    name: string,
    src: string,
    fname: string,
}


export const chpict : Array<pictitem> = [
    {name: "Болоньєзе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/sHypmOD-kUfrgzF-XjkkIBX.jpeg", fname: "kHQwIW-ntVDCRH-lFClLzQ.jpeg"},
    {name: "Паста з сирним соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kHQwIW-ntVDCRH-lFClLzQ.jpeg",fname:"tQnBFAM-cJsEUX-cSNvdLu.jpeg"},
    {name: "Паста карбонара",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tQnBFAM-cJsEUX-cSNvdLu.jpeg",fname:"WFHplDe-EfvaNWE-jQqhoU.jpeg"},
    {name: "Паста домашняя с куриным мясом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WFHplDe-EfvaNWE-jQqhoU.jpeg",fname:"RqHKNJq-LuqoKRN-sxQuVv.jpeg"},
    {name: "Салат з тунцем гриль і горіховим соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RqHKNJq-LuqoKRN-sxQuVv.jpeg",fname:"GAJOyTC-uxTIEcX-RCEwObx.jpeg"},
    {name: "Тайський салат з телятиною і рисовою локшиною",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GAJOyTC-uxTIEcX-RCEwObx.jpeg",fname:"XFeGXSt-GgQelxx-xftdmKt.jpeg"},
    {name: "Лаваш з індичкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/XFeGXSt-GgQelxx-xftdmKt.jpeg",fname:"MFUDkxe-SsGnqGA-wlxxMIR.jpeg"},
    {name: "Лаваш з моцарелою і зеленню",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/MFUDkxe-SsGnqGA-wlxxMIR.jpeg",fname:"QJLQsfV-fafcwSm-HlunInk.jpeg"},
    {name: "Лаваш з курячим філе і томатами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QJLQsfV-fafcwSm-HlunInk.jpeg",fname:"FVHpFyg-rBJnrpD-bLinkeD.jpeg"},
    {name: "Лаваш з телятиною і грибами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FVHpFyg-rBJnrpD-bLinkeD.jpeg",fname:"HudkNRA-eDnzkEj-TFpUDU.jpeg"},
    {name: "Лаваш з курячим стегном",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HudkNRA-eDnzkEj-TFpUDU.jpeg",fname:"LCZktrC-mTqFfgu-bfcJPpw.jpeg"},
    {name: "Лосось з овочами гриль",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/LCZktrC-mTqFfgu-bfcJPpw.jpeg",fname:"RfLNlDP-eIIDCwB-lDydCbV.jpeg"},
    {name: "Форель по-карпатски",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RfLNlDP-eIIDCwB-lDydCbV.jpeg",fname:"wYebCNy-JVlJhjN-EohrUBE.jpeg"},
    {name: "Рибна сковорідка",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/wYebCNy-JVlJhjN-EohrUBE.jpeg",fname:"NuEIGcL-rcfNmuW-JciiPdH.jpeg"},
    {name: "Крила фрі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/NuEIGcL-rcfNmuW-JciiPdH.jpeg",fname:"cHIHZkV-iQsDNbC-sJkJChk.jpeg"},
    {name: "Курка в кисло-солодкому соусі з чіпсами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/cHIHZkV-iQsDNbC-sJkJChk.jpeg",fname:"AeZloOw-twDmQCU-WlIQzm.jpeg"},
    {name: "Креветки фрі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/AeZloOw-twDmQCU-WlIQzm.jpeg",fname:"hHBJEHl-tqdVDQt-GxYLbfO.jpeg"},
    {name: "Тар-тар из телятины",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/hHBJEHl-tqdVDQt-GxYLbfO.jpeg",fname:"ASoIpBM-ylBMYeN-KJoEVkO.jpeg"},
    {name: "Свинина в гострому соусі з чіпсами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ASoIpBM-ylBMYeN-KJoEVkO.jpeg",fname:"AjmClGg-yhuANqu-zbTlxeR.jpeg"},
    {name: "Свинина барбекю з картоплею по-креольськи",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/AjmClGg-yhuANqu-zbTlxeR.jpeg",fname:"OFXuIdj-LbXymPK-CiTqXBD.jpeg"},
    {name: "Телятина на овочевій подушці з винним соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OFXuIdj-LbXymPK-CiTqXBD.jpeg",fname:"jRDbLgf-ZDYwCXk-xeqheIX.jpeg"},
    {name: "Стейк зі свинини з картопляним пюре і соусом сальса",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jRDbLgf-ZDYwCXk-xeqheIX.jpeg",fname:"IOYqreb-UtOlbZC-bCRGlTe.jpeg"},
    {name: "Тальята з телятини",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/IOYqreb-UtOlbZC-bCRGlTe.jpeg",fname:"FCLHlRq-ASZLTYO-ubMeAZp.jpeg"},
    {name: "Філе індички з овочевим рататуєм і трюфеля пастою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FCLHlRq-ASZLTYO-ubMeAZp.jpeg",fname:"CFbqqgr-KIIYSoq-breMOhU.jpeg"},
    {name: "Гриль сет Чилі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CFbqqgr-KIIYSoq-breMOhU.jpeg",fname:"lVnfkeh-bjngDz-BCwuYGn.jpeg"},
    {name: "Сковорідка з фермерськими ковбасками",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/lVnfkeh-bjngDz-BCwuYGn.jpeg",fname:"nJdrDt-SskFTjK-qGnHQyz.jpeg"},
    {name: "Сковорідка з курячими серцями і печінкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nJdrDt-SskFTjK-qGnHQyz.jpeg",fname:"laRNQPF-tXdRwBl-wuudkXt.jpeg"},
    {name: "Сковорідка по-домашньому",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/laRNQPF-tXdRwBl-wuudkXt.jpeg",fname:"ZCLopEb-IInFONb-cSGAIbw.jpeg"},
    {name: "Сковорідка з курячим стегном і трюфельноей пастою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ZCLopEb-IInFONb-cSGAIbw.jpeg",fname:"tyNeBHk-sTIcJOt-UldGCKM.jpeg"},
    {name: "Cковорідка польова",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tyNeBHk-sTIcJOt-UldGCKM.jpeg",fname:"OsDEdaI-xbiZFFy-oWLpUlG.jpeg"},
    {name: "Грецький300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OsDEdaI-xbiZFFy-oWLpUlG.jpeg",fname:"TgoIWZb-jFIvmPL-MYsrHzZ.jpeg"},
    {name: "Грін-мікс з курячим філе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TgoIWZb-jFIvmPL-MYsrHzZ.jpeg",fname:"HgbRFQF-aguoLIs-VLclHvH.jpeg"},
    {name: "Цезарь люкс",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HgbRFQF-aguoLIs-VLclHvH.jpeg",fname:"FjWzkLN-ClpIIY-HefXIDz.jpeg"},
    {name: "Салат з ростбіфом і цукіні гриль",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FjWzkLN-ClpIIY-HefXIDz.jpeg",fname:"kiQHtff-sFGIur-ritKnJT.jpeg"},
    {name: "Салат з телятиною і печерицями",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kiQHtff-sFGIur-ritKnJT.jpeg",fname:"CkmDFqk-HDpZIPk-WAnINTU.jpeg"},
    {name: "М'ясний салат",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CkmDFqk-HDpZIPk-WAnINTU.jpeg",fname:"QGfTLJp-TnKQIkR-emoFJiH.jpeg"},
    {name: "Грецький 200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QGfTLJp-TnKQIkR-emoFJiH.jpeg",fname:"zGJbGfF-GIADJUJ-CpFtcRD.jpeg"},
    {name: "Салат з камамбером фрі і апельсином",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/zGJbGfF-GIADJUJ-CpFtcRD.jpeg",fname:"dNIHMef-sXVvVDF-IkEqwZW.jpeg"},
    {name: "Цезарь 	200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dNIHMef-sXVvVDF-IkEqwZW.jpeg",fname:"buRMwU-kbouGrF-kmLgiDD.jpeg"},
    {name: "Цезарь 	300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/buRMwU-kbouGrF-kmLgiDD.jpeg",fname:"TgkkIw-QbqIvJg-RtmoSQl.jpeg"},
    {name: "Салат з кіноа, авокадо і сиром фета",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TgkkIw-QbqIvJg-RtmoSQl.jpeg",fname:"qxJlXxB-bsyNJem-NFuXUzO.jpeg"},
    {name: "Фірмовий олів'є з лососем і креветками",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/qxJlXxB-bsyNJem-NFuXUzO.jpeg",fname:"HoIxIgH-DaGFAhs-FyDFTHc.jpeg"},
    {name: "Салат з курячим філе гриль і кедровими горіхами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HoIxIgH-DaGFAhs-FyDFTHc.jpeg",fname:"bOlDelJ-QjAVml-SIHyGJC.jpeg"},
    {name: "Грузинський",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bOlDelJ-QjAVml-SIHyGJC.jpeg",fname:"ZrHWiKO-NIQsLvU-QpLfZwa.jpeg"},
    {name: "Салат з курячою печінкою і свіжими томатами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ZrHWiKO-NIQsLvU-QpLfZwa.jpeg",fname:"nfDnhX-CkvdCSl-neStVgg.jpeg"},
    {name: "Гавайський з курячим філе і ананасами",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nfDnhX-CkvdCSl-neStVgg.jpeg",fname:"oelGoKI-pNhDQY-FzkGQFb.jpeg"},
    {name: "Овочевий мікс200гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/oelGoKI-pNhDQY-FzkGQFb.jpeg",fname:"yHJXmKF-hPCzRip-qsrHCol.jpeg"},
    {name: "Овочевий Мікс 300гр",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/yHJXmKF-hPCzRip-qsrHCol.jpeg",fname:"ikkgegJ-CHViSLG-DikDlo.jpeg"},
    {name: "З курячим філе і вершковим соусом каррі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ikkgegJ-CHViSLG-DikDlo.jpeg",fname:"HhCJJJs-lIqenMI-Ousrkl.jpeg"},
    {name: "Сільська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/HhCJJJs-lIqenMI-Ousrkl.jpeg",fname:"aGQHDfF-dYismDU-JgwucDF.jpeg"},
    {name: " Грецька",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/aGQHDfF-dYismDU-JgwucDF.jpeg",fname:"ueTbCIr-YVHcLjP-JCYlVO.jpeg"},
    {name: "Мисливська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ueTbCIr-YVHcLjP-JCYlVO.jpeg",fname:"pxbDFVk-OskQWfJ-SKHJiZr.jpeg"},
    {name: "Формаджо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/pxbDFVk-OskQWfJ-SKHJiZr.jpeg",fname:"jdrXycr-fCKxeLX-bCJkltx.jpeg"},
    {name: "М'ясна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jdrXycr-fCKxeLX-bCJkltx.jpeg",fname:"iNzeFwy-cixRCdP-ClHCWkd.jpeg"},
    {name: "Чориззо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iNzeFwy-cixRCdP-ClHCWkd.jpeg",fname:"EOJeBQV-hoiWqBM-yIiIILP.jpeg"},
    {name: "Міланська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/EOJeBQV-hoiWqBM-yIiIILP.jpeg",fname:"ooyBcKQ-OeJKmIM-pVelpGd.jpeg"},
    {name: "Сомбреро",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ooyBcKQ-OeJKmIM-pVelpGd.jpeg",fname:"WjEwRcD-IqTMdGS-PbxAkHC.jpeg"},
    {name: "Ароматна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WjEwRcD-IqTMdGS-PbxAkHC.jpeg",fname:"FuWkilt-tyPdUI-MtCHsqC.jpeg"},
    {name: "Барбекю",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FuWkilt-tyPdUI-MtCHsqC.jpeg",fname:"DkpCGDC-PptctgF-zrDqQuA.jpeg"},
    {name: "Гавайська",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DkpCGDC-PptctgF-zrDqQuA.jpeg",fname:"TeGgCCk-DzXKTPQ-yYDuDVr.jpeg"},
    {name: "Кальцоне з шинкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/TeGgCCk-DzXKTPQ-yYDuDVr.jpeg",fname:"JUvEIDD-pUxGlLC-fyTljcQ.jpeg"},
    {name: "Кальцоне з курячим філе",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JUvEIDD-pUxGlLC-fyTljcQ.jpeg",fname:"DjdTZmf-EkLeGol-JBJFzQN.jpeg"},
    {name: "Кальцоне сирна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DjdTZmf-EkLeGol-JBJFzQN.jpeg",fname:"dAFIjxv-oVdbCYv-LtdesJV.jpeg"},
    {name: "Пепероні",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dAFIjxv-oVdbCYv-LtdesJV.jpeg",fname:"QGGbLVM-ixlowJ-CmjieHY.jpeg"},
    {name: "Чілі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QGGbLVM-ixlowJ-CmjieHY.jpeg",fname:"zFpVCCy-WlRIOvT-JpIjTyv.jpeg"},
    {name: "Салямі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/zFpVCCy-WlRIOvT-JpIjTyv.jpeg",fname:"VteGlsx-bbfNXs-GkTfKXT.jpeg"},
    {name: "Поло",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/VteGlsx-bbfNXs-GkTfKXT.jpeg",fname:"kfpcksb-QfpewN-eZxjwHx.jpeg"},
    {name: "Прошутто",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kfpcksb-QfpewN-eZxjwHx.jpeg",fname:"eCPiqmc-coDtqix-bjKbuXv.jpeg"},
    {name: "Тонато",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/eCPiqmc-coDtqix-bjKbuXv.jpeg",fname:"WjRHDkb-hipysIK-bHZkeEy.jpeg"},
    {name: "Цезарь",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WjRHDkb-hipysIK-bHZkeEy.jpeg",fname:"pkClOo-CYCIKIC-yRPsCUG.jpeg"},
    {name: "Сан-марино",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/pkClOo-CYCIKIC-yRPsCUG.jpeg",fname:"qnWTrq-FjwHeyr-hZJokD.jpeg"},
    {name: "Ростбіф",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/qnWTrq-FjwHeyr-hZJokD.jpeg",fname:"wrRBONR-WytwBk-xTtzvoj.jpeg"},
    {name: "Вилладжіо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/wrRBONR-WytwBk-xTtzvoj.jpeg",fname:"dHGRWo-kaJdFJU-bcbkGKm.jpeg"},
    {name: "Аматрічіано",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dHGRWo-kaJdFJU-bcbkGKm.jpeg",fname:"dUGuaRl-UeCjbQM-ZApxqHP.jpeg"},
    {name: "Сирна",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dUGuaRl-UeCjbQM-ZApxqHP.jpeg",fname:"klMlqCh-jnbEPPu-JsBmegb.jpeg"},
    {name: "Б 'ьянка",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/klMlqCh-jnbEPPu-JsBmegb.jpeg",fname:"XOqYkCI-IzUChXU-nyEtHe.jpeg"},
    {name: "Сан-Ремо + бутилка вина Villa Krim ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/XOqYkCI-IzUChXU-nyEtHe.jpeg",fname:"MBTMFuk-QdgwZHG-swgHbeA.jpeg"},
    {name: "Палермо + 2л пива Carlsberg",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/MBTMFuk-QdgwZHG-swgHbeA.jpeg",fname:"tQNIFfI-lkGjvcG-eeQPCzC.jpeg"},
    {name: "Наполі	+ 2л пива Kronenbourg Blanc",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/tQNIFfI-lkGjvcG-eeQPCzC.jpeg",fname:"fuGesk-HnEAGH-skBZDDu.jpeg"},
    {name: "Нуталина (солодка  піца)",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/fuGesk-HnEAGH-skBZDDu.jpeg",fname:"YolSQIA-kThxDbZ-YmHgHEc.jpeg"},
    {name: "Йору",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/YolSQIA-kThxDbZ-YmHgHEc.jpeg",fname:"Aujrrck-cgURtxa-WdFDRFS.jpeg"},
    {name: "Запечений зелений дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/Aujrrck-cgURtxa-WdFDRFS.jpeg",fname:"GSWrHSl-DDFjwCN-GmHyHkL.jpeg"},
    {name: "Імбирний рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GSWrHSl-DDFjwCN-GmHyHkL.jpeg",fname:"VUllXxV-eACumIm-FgIAmyk.jpeg"},
    {name: "Зелений дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/VUllXxV-eACumIm-FgIAmyk.jpeg",fname:"GwzjkxJ-kRJpCDf-htqRkcl.jpeg"},
    {name: "Томаго",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/GwzjkxJ-kRJpCDf-htqRkcl.jpeg",fname:"CjMljcK-RjXBRo-BqSTELB.jpeg"},
    {name: "Кани",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/CjMljcK-RjXBRo-BqSTELB.jpeg",fname:"SHbCOmH-FIwtblW-JQnykAc.jpeg"},
    {name: "Парма рол з креветкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/SHbCOmH-FIwtblW-JQnykAc.jpeg",fname:"QKCbDsI-kJDFxLi-NBWsurb.jpeg"},
    {name: "Кудамон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/QKCbDsI-kJDFxLi-NBWsurb.jpeg",fname:"DgCGbwV-RmHkuHE-uVZhmFb.jpeg"},
    {name: "Фудзі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DgCGbwV-RmHkuHE-uVZhmFb.jpeg",fname:"jZgbceS-HlJuURx-UjmoLrG.jpeg"},
    {name: "Самурай",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/jZgbceS-HlJuURx-UjmoLrG.jpeg",fname:"iDUmHVt-FvHoXZ-THvtHBx.jpeg"},
    {name: "Інь-янь",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iDUmHVt-FvHoXZ-THvtHBx.jpeg",fname:"WoCeIUt-bmwIDCk-KNvJHMc.jpeg"},
    {name: "Чидорі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/WoCeIUt-bmwIDCk-KNvJHMc.jpeg",fname:"bpHliyz-ikGneyv-dIBUOQG.jpeg"},
    {name: "Філадельфія",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bpHliyz-ikGneyv-dIBUOQG.jpeg",fname:"xZOYDqW-BUDxYpk-SIlXHUR.jpeg"},
    {name: "Золотий дракон",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/xZOYDqW-BUDxYpk-SIlXHUR.jpeg",fname:"hvDZyG-TDnQfIg-EReQpja.jpeg"},
    {name: "Гадо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/hvDZyG-TDnQfIg-EReQpja.jpeg",fname:"YPGsato-SeUxlXO-bHxIWLO.jpeg"},
    {name: "Унагі хая",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/YPGsato-SeUxlXO-bHxIWLO.jpeg",fname:"OHrJfVT-ZCctvTR-seNuqWk.jpeg"},
    {name: "Туна рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/OHrJfVT-ZCctvTR-seNuqWk.jpeg",fname:"abmpDwT-smmykdT-bwHkrH.jpeg"},
    {name: "Радуйга",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/abmpDwT-smmykdT-bwHkrH.jpeg",fname:"lBUHsb-LknrLPc-gzyyDrV.jpeg"},
    {name: "Філадельфія хаяші",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/lBUHsb-LknrLPc-gzyyDrV.jpeg",fname:"bXXjzDo-oLayEse-VnkDMNo.jpeg"},
    {name: "Такусан",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/bXXjzDo-oLayEse-VnkDMNo.jpeg",fname:"ARpgtSA-ncRkkwl-eFgbJMo.jpeg"},
    {name: "Дайкон ролл",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/ARpgtSA-ncRkkwl-eFgbJMo.jpeg",fname:"iDroSjC-ISfODJb-zsbIkHQ.jpeg"},
    {name: "Овара",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/iDroSjC-ISfODJb-zsbIkHQ.jpeg",fname:"dLPKVkw-YfDGoSg-LFmesIl.jpeg"},
    {name: "Філадельфія з кокосовим соусом",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/dLPKVkw-YfDGoSg-LFmesIl.jpeg",fname:"JOeozjD-ZFuLjAl-MVozHr.jpeg"},
    {name: "Чілі рол",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JOeozjD-ZFuLjAl-MVozHr.jpeg",fname:"mDiMMgg-JqZzjJh-IgxtqkL.jpeg"},
    {name: "Широ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/mDiMMgg-JqZzjJh-IgxtqkL.jpeg",fname:"NhwAXFQ-UTYLIuq-GLIgeJk.jpeg"},
    {name: "Запечена рол з лососем",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/NhwAXFQ-UTYLIuq-GLIgeJk.jpeg",fname:"FOKOxfP-TQvbtFx-XwCvbAy.jpeg"},
    {name: "Сет Муракамі",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FOKOxfP-TQvbtFx-XwCvbAy.jpeg",fname:"nloUvYV-PbzLLG-TIIiGJX.jpeg"},
    {name: "Сет Хоккайдо",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/nloUvYV-PbzLLG-TIIiGJX.jpeg",fname:"FCnbODF-WyieuXv-WqKXGDl.jpeg"},
    {name: "Сет Окінава",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/FCnbODF-WyieuXv-WqKXGDl.jpeg",fname:"DorGJWY-GQhJFHp-bVGObhD.jpeg"},
    {name: "Сет нагоя",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/DorGJWY-GQhJFHp-bVGObhD.jpeg",fname:"RNHDkHt-eoeSFYW-tuyfnhh.jpeg"},
    {name: "З качкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/RNHDkHt-eoeSFYW-tuyfnhh.jpeg",fname:"JydVFg-IkfwFyp-qCVzNNC.jpeg"},
    {name: "З куркою ",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/JydVFg-IkfwFyp-qCVzNNC.jpeg",fname:"kDebNDR-VskPCXW-ZQoqhr.jpeg"},
    {name: "Гостра зі свининою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/kDebNDR-VskPCXW-ZQoqhr.jpeg",fname:"LNkmvJe-anktrID-gnzIZFA.jpeg"},
    {name: "З креветкою",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/LNkmvJe-anktrID-gnzIZFA.jpeg",fname:"yonyPmV-yjaKem-kJIOFvc.jpeg"},
    {name: "З телятиною",src:"https://prod-eat-media.s3.eu-central-1.amazonaws.com/prod-eat-chilipizza/menu/yonyPmV-yjaKem-kJIOFvc.jpeg",fname:""},
    
]